#!/bin/bash
set -x #echo on

. ./config.sh
../../../bisq-desktop   --baseCurrencyNetwork=BTC_REGTEST --useLocalhostForP2P=true --useDevPrivilegeKeys=true --nodePort=5555 --appName=bisq-BTC_REGTEST_Alice --daoActivated=$dao --genesisBlockHeight=$genesis_height --genesisTxId=$genesis_tx --fullDaoNode=false --rpcUser=$rpcuser --rpcPassword=$rpcpassword --rpcBlockNotificationPort=$blocknotifyport

 

