#!/bin/bash

set -x #echo on
. ./config.sh
#../../../bisq-seednode --baseCurrencyNetwork=BTC_REGTEST --useLocalhostForP2P=true --useDevPrivilegeKeys=true --nodePort=2002 --appName=bisq-BTC_REGTEST_Seed_2002 --daoActivated=true --genesisBlockHeight=$genesis_height --genesisTxId=$genesis_tx --fullDaoNode=$dao --rpcUser=$rpcuser --rpcPassword=$rpcpassword --rpcPort=$rpcport --rpcBlockNotificationPort=$blocknotifyport
# removed --daoActivated=true 

../../../bisq-seednode --baseCurrencyNetwork=BTC_REGTEST --useLocalhostForP2P=true --useDevPrivilegeKeys=true --fullDaoNode=$dao --rpcUser=$rpcuser --rpcPassword=$rpcpassword --rpcBlockNotificationPort=$blocknotifyport --nodePort=3002 --userDataDir=. --appName=seednode2 --genesisBlockHeight=$genesis_height --genesisTxId=$genesis_tx

